language: python

python:
  - 2.7

notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    on_success: always
    on_failure: always

install: "pip install -r requirements.txt"

script: python tests/tests.py

